version: "3.5"
services:
  clef:
    image: ethersphere/clef:0.6.0
    user: 1000:1000
    volumes:
      - /mnt/Scorpion/abi-cluster/test/clef:/home/ethereum/.clef
      - /mnt/Scorpion/abi-cluster/test/geth:/home/ethereum/.ethereum
      - /mnt/Raiden/abi-cluster/test/geth:/home/ethereum/.ethereum/keystore
    # chain 5 = goerli
    command: --chainid 5
    restart: unless-stopped

  geth:
    image: docker.gbre.org/ethereum
    build: ./ethereum
    user: 1000:1000
    ports:
      - 30303:30303
      - 8545:8545
    volumes:
      - /mnt/Scorpion/abi-cluster/test/clef:/home/ethereum/.clef
      - /mnt/Scorpion/abi-cluster/test/geth:/home/ethereum/.ethereum
      - /mnt/Raiden/abi-cluster/test/geth:/home/ethereum/.ethereum/keystore
    command: --goerli --http --signer=.clef/clef.ipc
    restart: unless-stopped
